### ISSUE TITLE
No prompt for username after invoking `yubiauthadmin add`

### ISSUE THREAD

**Issue by jmhthethird** [blueboxgroup/yubiauthd#10]
When invoking cmd for adding new user I am not prompted for username or any next step.

Repro steps:
```bash
> sudo su -
> yubiauthadmin add
yubiauthadmin <action> <arguments>
Actions:
        list - lists the yubiauth identities
        add
> echo $?
1
```
I have tried passing a new username argument after the `yubiauthadmin add` statement but would always get the same result.

**Comment by dlundquist** [comment]
Thanks for reporting. The add action takes an argument of the new Yubikey's one time passsword. `usage()` needs to check the `context` variable and provide specific help in this case. Perhaps a hash of usage messages by context.
